name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#   - name: Build the Docker image
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: pennsignals/publish_docker-compose@v0.1.0
      with:
        docker_compose: 'docker-compose.yml'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"

  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: {repository-owner}/{repository-name}
          files: |
            _README.md=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
